ALTER TABLE rail_requests ALTER COLUMN amount TYPE DOUBLE PRECISION USING amount::DOUBLE PRECISION;
ALTER TABLE rail_settlements ALTER COLUMN amount TYPE DOUBLE PRECISION USING amount::DOUBLE PRECISION;
ALTER TABLE rail_chargebacks ALTER COLUMN amount TYPE DOUBLE PRECISION USING amount::DOUBLE PRECISION;