ALTER TABLE rail_requests ALTER COLUMN amount TYPE NUMERIC USING amount::NUMERIC;
ALTER TABLE rail_settlements ALTER COLUMN amount TYPE NUMERIC USING amount::NUMERIC;
ALTER TABLE rail_chargebacks ALTER COLUMN amount TYPE NUMERIC USING amount::NUMERIC;